### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by frenibo** [frenibo/roomfinder#4]
**Raumview**

- [x] Bilder für Räume mit roter Makierung (Grundriss) --> Kaja
- [x]  Zoom // Frederic
- [x] 	Toggel über Geschosse --> Logik, dass das richtige Bild angezeigt wird --> Kaja
- [x] 	Info-Icon Pop-Up Dialog  //Frederic
- [ ] Dialog-Info-Building mit Content füllen + CSS
- [ ] 	Dreier Buttons anpassen

**Belegungsplan**
	
- [x] Switch um Tag auszuwählen // Frederic
- [ ] Leiste mit Uhrzeit und Belegungen
- [ ] Info-Bar über Raum
- [ ] Dreier-Buttons

**EInstellungen**
- [x] Component erstellen //Frederic
- [ ] Räume freischalten

**Freie Räume**
	
- [x]  Suchleiste //Frederic
- [x] 	Kalender zum Datum auswählen //Frederic
- [x] 	Kachel-View für die freien Räume //Frederic
- [ ] 	Button für freigeschaltete Räume

**Gebäudenasicht**
	
- [ ]  Toggeln über Bilder (Logik)
- [ ]  Info-Bar erstellen mit Google-Maps-Button
- [x] Dreier-Buttons erstellen
- [ ]  Map mit Gebäude --> Kaja

**Header**

- [ ] Stern weiter nach links, mehr Abstand zum Rand //Frederic
- [ ] Scale von Überschriften //Frederic
- [ ] Scale von Zurück-Button //Frederic

**Favoriten**

- [ ] Cookies funktionieren bei Android nicht  //Frederic

**Dreier-Buttons**
	
- [ ] angepasst auf aktuelle View
- [ ] Icons hinzufügen

**Info-Bar**
	
- [ ]  angepasst auf aktuelle View
- [ ] 	Info Button größer
- [ ] 	Raumname Fett
- [ ]  Zeilenabstand anpassen
- [ ] 	Schriftart anpassen

**Gebäudesuchen**

- [x] Bild-Bubble für Gebäude //Frederic

**Android-App**

- [ ] .apk exportieren und auf Android Phon installieren. //Frederic

**Favoriten**

- [ ] Struktur an Figma anpassen
